version: '3'
services: 
  app:
    container_name: laravel # 
    build: ./docker/php
    volumes:
      - ./src:/var/www
  nginx: 
    image: nginx
    container_name: nginx
    ports:
      - 80:80 # 8000はコンテナの外からの通信を受けるためのポート番号。80はコンテナ内通信を受けるためのポート番号
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf # :より左がホスト側のファイルで右側がコンテナ内のファイル
    working_dir: /var/www
    depends_on:
      - app
  db:
    image: mysql:8.0.36
    container_name: db
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:  
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf 
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin
    environment:
    - PMA_USER=root
    - PMA_PASSWORD=password
    ports:
    - 8080:80
