version: '3'
services: 
  app:
    container_name: laravel # 
    build: ./docker/php
    volumes:
      - ./src:/var/www
  nginx: 
    image: nginx
    container_name: nginx
    ports:
      - 80:80 # 8000はコンテナの外からの通信を受けるためのポート番号。80はコンテナ内通信を受けるためのポート番号
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf # :より左がホスト側のファイルで右側がコンテナ内のファイル
    working_dir: /var/www
    depends_on:
      - app
